site_name: HexViewer Documentation
site_url: https://facelessuser.github.io/HexViewer
repo_url: https://github.com/facelessuser/HexViewer
edit_uri: tree/master/docs/src/markdown
site_description: A Sublime Text hex viewer and editor.
copyright: Copyright &copy; 2011 - 2017 <a href="https://github.com/facelessuser">Isaac Muse</a>

pages:
  - User Guide: index.md
  - Installation: installation.md
  - Contributing &amp; Support: contributing.md
  - License: license.md

theme: material
docs_dir: docs/src/markdown
theme_dir: docs/theme

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: "\ue157"
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - pymdownx.extrarawhtml:
  - pymdownx.superfences:
  - pymdownx.highlight:
      css_class: codehilite
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
  - pymdownx.inlinehilite:
  - pymdownx.magiclink:
      repo_url_shortener: true
      base_repo_url: https://github.com/facelessuser/HexViewer
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.plainhtml:
      strip_attributes: ''
  - pymdownx.snippets:
      base_path: docs/src/markdown/_snippets
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:

extra:
  logo:
    icon: description
  palette:
    primary: blue
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  social:
    - type: github
      link: https://github.com/facelessuser
extra_css:
  - extra-21c736e569.css
extra_javascript:
  - extra-4596f9831a.js
