site_name: HexViewer Documentation
repo_url: https://github.com/facelessuser/HexViewer
site_description: A Sublime Text hex viewer and editor.
copyright: Copyright &copy; 2011 - 2015 <a href="https://github.com/facelessuser">Isaac Muse</a>
pages:
- ['index.md', 'Home']
- ['usage.md', 'User Guide']
- ['license.md', 'License']
